# import turtle
# from turtle import Turtle
# abc=Turtle()
# xyz=Turtle()
# abc.forward(100)
# xyz.back(200)
# turtle.exitonclick()
from turtle import Turtle,Screen
abc=Turtle()
s1=Screen()
abc.shape("turtle")
# abc.pencolor("red")
# abc.fillcolor("green")
abc.color("red","black")
abc.pensize(10)
abc.begin_fill()
abc.circle(100)
abc.end_fill()
abc.right(90)
abc.hideturtle()
abc.penup()
abc.forward(100)
abc.pendown()
abc.fillcolor("green")
abc.begin_fill()
abc.circle(50)
abc.end_fill()
abc.goto(-100,-100)
abc.showturtle()

s1.exitonclick()
