data=[
    {"name":"Surya",
     "follow count":400000,
     "Description":"Actor",
     "Country":"India"},
    {"name": "Virat",
     "follow count":1000000 ,
     "Description": "Cricketer",
     "Country": "India"},
    {"name": "Warner",
     "follow count":30000,
    "Description": "Cricketer",
    "Country": "Australia"},
    {"name": "Dhoni",
     "follow count":80000 ,
     "Description": "Cricketer and former",
     "Country": "India"},

    {"name": "Sachin",
     "follow count": 60000,
     "Description": "Cricketer",
     "Country": "India"},
    {"name": "Modi",
     "follow count": 50000,
     "Description": "Politician",
     "Country": "India"},
    {"name": "Vijay",
     "follow count":80000 ,
     "Description": "Actor,Politician",
     "Country": "India"},
    {"name": "Ajith",
     "follow count":5000 ,
     "Description": "Actor,Racer",
     "Country": "India"}

]
